baseURL = "https://fireact.dev/"
title = "fireact.dev"
theme = "hugo-universal-theme"
languageCode = "en-us"
defaultContentLanguage = "en"

# Enable comments by entering your Disqus shortname
disqusShortname = ""

# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

# number of words of summarized post content (default 70)
summaryLength = 70

[menu]
    [[menu.main]]
        name       = "Home"
        identifier = "menu.home"
        url        = "/"
        weight     = 1

    [[menu.main]]
        name       = "Demos"
        identifier = "menu.demos"
        url        = "/demos/"
        weight     = 2
        
    [[menu.main]]
        name       = "Blog"
        identifier = "menu.blog"
        url        = "/blog/"
        weight     = 3

    [[menu.main]]
        name       = "GitHub"
        identifier = "menu.github"
        url        = "https://github.com/fireact-dev/main"
        weight     = 4

[params]
    style = "default"
    logo = "img/logo.svg"
    logo_small = "img/logo.svg"
    logo_width = "40px"
    logo_height = "40px"
    about_us = "fireact.dev is an open-source framework for building SaaS applications with Firebase, React, TypeScript, and Stripe integration."
    copyright = "Copyright (c) 2024, fireact.dev; all rights reserved."
    date_format = "January 2, 2006"
    defaultKeywords = ["firebase", "react", "typescript", "saas", "stripe", "tailwindcss"]
    defaultDescription = "Open-source framework for building SaaS applications with Firebase, React, TypeScript, and Stripe"

    # Contact form configuration
    email = "contact@fireact.dev"

    [params.carousel]
        enable = true
        background = "dark"

    [params.features]
        enable = true

    [params.see_more]
        enable = true
        icon = "fab fa-github"
        title = "Join Our Open Source Community"
        subtitle = "Contribute to fireact.dev and help shape the future of SaaS development. Access our comprehensive documentation, engage with fellow developers, and build amazing products together."
        link_url = "https://github.com/fireact-dev/main"
        link_text = "Explore on GitHub"

    [params.clients]
        enable = false

    [params.recent_posts]
        enable = true
        title = "Latest Updates"
        subtitle = "Stay up to date with the latest news, features, and improvements to the fireact.dev framework."

    [params.topbar]
        enable = false
        text = ""

    [params.footer]
        enable = true
