baseURL = "http://localhost:1313/"
title = "My New Hugo Site"
theme = "hugo-universal-theme"
languageCode = "en-us"
defaultContentLanguage = "en"

# Enable comments by entering your Disqus shortname
disqusShortname = ""

# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

# number of words of summarized post content (default 70)
summaryLength = 70

[menu]
    [[menu.main]]
        name       = "Home"
        identifier = "menu.home"
        url        = "/"
        weight     = 1

    [[menu.main]]
        name       = "Blog"
        identifier = "menu.blog"
        url        = "/blog/"
        weight     = 2

[params]
    style = "default"
    logo = "img/logo.png"
    logo_small = "img/logo-small.png"
    about_us = "We are a creative studio founded in New York. We create meaningful digital experiences."
    copyright = "Copyright (c) 2024, Your Company; all rights reserved."
    date_format = "January 2, 2006"
    defaultKeywords = ["devows", "hugo", "go"]
    defaultDescription = "Site template made by Devcows using Hugo"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    email = "your@email.com"

    [params.carousel]
        enable = true

    [params.features]
        enable = true

    [params.see_more]
        enable = true
        icon = "far fa-file-alt"
        title = "Do you want to see more?"
        subtitle = "We have prepared for you more than 40 different HTML pages, including 5 variations of homepage."
        link_url = "#"
        link_text = "Check other homepages"

    [params.clients]
        enable = true
        title = "Our Clients"
        subtitle = ""

    [params.recent_posts]
        enable = true
        title = "From our blog"
        subtitle = "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo."

    [params.topbar]
        enable = true
        text = """<p class="hidden-sm hidden-xs">Contact us on +420 777 555 333 or hello@universal.com.</p>
        <p class="hidden-md hidden-lg"><a href="tel:+420 777 555 333" data-animate-hover="pulse"><i class="fas fa-phone"></i></a>
        <a href="mailto:hello@universal.com" data-animate-hover="pulse"><i class="fas fa-envelope"></i></a>
        </p>
        """

    [params.footer]
        enable = true
